GET http://localhost:8080/api/city
###
GET http://localhost:8080/api/city/3
###
POST http://localhost:8080/api/city
Content-Type: application/json

{
  "id": 1,
  "name": "London",
  "country": "United Kingdom",
  "details": "The British capital"
}
###
POST http://localhost:8080/api/city
Content-Type: application/json

{
  "id": 3,
  "name": "Paris",
  "country": "France",
  "details": "Home to the Eiffel Tower!"
}
###
PUT http://localhost:8080/api/city/3
Content-Type: application/json

{
  "id": 3,
  "name": "Madrid",
  "country": "Spain",
  "details": "A warm country!"
}
###
DELETE http://localhost:8080/api/city/1
