GET http://localhost:8080/api/trip
###
GET http://localhost:8080/api/trip/3
###
POST http://localhost:8080/api/trip
Content-Type: application/json

{
  "city": {
    "id": 1
  },
  "startDate": "2026-01-01",
  "endDate": "2026-01-01",
  "rating": 5,
  "personalNotes": "Was great"
}
###
POST http://localhost:8080/api/city
Content-Type: application/json

{
  "id": 3,
  "name": "Paris",
  "country": "France",
  "details": "Home to the Eiffel Tower!"
}
###
PUT http://localhost:8080/api/city/3
Content-Type: application/json

{
  "id": 3,
  "name": "Madrid",
  "country": "Spain",
  "details": "A warm country!"
}
###
DELETE http://localhost:8080/api/city/1
